package main

var urls = []string{
	"https://coastroad.net",
	"https://facebook.com",
	"https://google.com",
	"https://github.com",
	"http://haust.edu.cn",
	"https://www.qq.com",
	"https://qlcoud.tencent.com",
	"https://app.cloudcone.com",
	"https://baidu.com",
	"https://youtube.com",
	"https://youku.com",
	"http://tudou.com",
	"https://pornhub.com",
	"https://xvideos.com",
	"https://www.taobao.com",
	"https://www.tmall.com",
	"https://apple.com",
	"https://volvocar.com",
	"https://bmw.com",
	"https://bilibili.com",
	"https://lynkco.com.cn",
	"https://zhihu.com",
	"https://www.porsche.com",
	"https://instagram.com",
	"https://www.usa.gov/",
	"https://www.whitehouse.gov/",
	"https://www.nike.com",
	"https://adidas.com",
	"https://kapa.com",
	"https://www.converse.com/us/en_us/c/converse",
}
